services:
  backend:
    build: ./backend
    container_name: habit-backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/habit-tracker
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    networks:
      - habit-net

  frontend:
    build: ./frontend
    container_name: habit-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://habit-backend:3000
    depends_on:
      - backend
    networks:
      - habit-net

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - habit-net

networks:
  habit-net:
    driver: bridge
